# Generated by Django 4.0.2 on 2022-03-30 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtag',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='page',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='CardTag',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
