# Generated by Django 4.0.2 on 2022-03-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a01_note', '0005_remove_deck_deck_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.TextField(choices=[('0', 'New'), ('1', 'Learning'), ('2', 'To review')], default='0', max_length=1),
        ),
    ]
