# Generated by Django 4.0.2 on 2022-03-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a01_note', '0007_alter_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='hex_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
