# Generated by Django 4.0.2 on 2022-03-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a01_note', '0008_alter_page_hex_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='hex_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
