# Generated by Django 4.0.2 on 2022-04-11 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a01_note', '0011_remove_cardtag_cards_remove_deck_page_delete_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_status',
        ),
    ]
