# Generated by Django 4.0.2 on 2022-04-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a01_note', '0012_remove_page_page_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
