# Generated by Django 4.0.2 on 2022-04-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a01_note', '0017_access_page_guest_users_access_page_access_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_role',
            field=models.CharField(choices=[('0', 'Folder'), ('1', 'Note'), ('2', 'Folder and Note')], default='0', max_length=1),
        ),
    ]
