# Generated by Django 4.0.2 on 2022-04-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a01_note', '0018_alter_page_page_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='sharing_code',
        ),
    ]
