# Generated by Django 4.0.2 on 2022-04-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a01_note', '0019_remove_page_sharing_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sharing_code',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
