# Generated by Django 4.0.2 on 2022-07-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a01_note', '0020_page_sharing_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cie10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(blank=True, max_length=250, null=True)),
                ('diagnostic', models.CharField(blank=True, max_length=250, null=True)),
                ('risk_factor', models.CharField(blank=True, max_length=250, null=True)),
                ('prevention', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cie10', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a01_note.cie10')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('concentration', models.CharField(max_length=250)),
                ('pharmaceutical_form', models.CharField(max_length=250)),
                ('pharmaceutical_short_form', models.CharField(max_length=250)),
                ('presentation', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('contact', models.CharField(choices=[('D', 'Direct'), ('I', 'Indirect')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[(None, 'Choose a type'), ('D', 'Disease')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a01_note.page')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('sex', models.CharField(choices=[(None, 'Choose a related sex'), ('M', 'Male'), ('F', 'Female'), ('B', 'Both male and female')], max_length=1)),
                ('disease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='a01_note.disease')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='drug',
            field=models.ManyToManyField(to='a01_note.Drug'),
        ),
        migrations.AddField(
            model_name='disease',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a01_note.summary'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptom',
            field=models.ManyToManyField(to='a01_note.Symptom'),
        ),
        migrations.AddField(
            model_name='disease',
            name='transmissionmode',
            field=models.ManyToManyField(to='a01_note.TransmissionMode'),
        ),
    ]
