# Generated by Django 4.0.2 on 2022-07-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a01_note', '0021_cie10_disease_drug_symptom_transmissionmode_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary_type',
            field=models.CharField(choices=[(None, 'Choose a type'), ('0', 'Disease')], max_length=1),
        ),
    ]
