# Generated by Django 4.0.2 on 2022-07-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a01_note', '0022_alter_summary_summary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='summary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='a01_note.summary'),
        ),
    ]
