# Generated by Django 4.0.2 on 2022-07-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a01_note', '0023_alter_disease_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='max_age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disease',
            name='min_age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disease',
            name='sex',
            field=models.CharField(choices=[(None, 'Choose a related sex'), ('M', 'Male'), ('F', 'Female'), ('B', 'Both male and female')], default='B', max_length=1),
        ),
        migrations.DeleteModel(
            name='DiseaseConstraint',
        ),
    ]
